### ISSUE TITLE
[BUG] Template mail alert from httpcheck_web_service_unreachable say example.com on any job

### ISSUE THREAD

**Issue by cgnunezbantics** [netdata/netdata-cloud#130]
Hello. Great job.
I test alerts and saw a confusous mails.

In the template mail alert from httpcheck_web_service_unreachable say "example.com" on any job

To Reproduce, Create a httpcheck job and trigger the alert. The mail send have hardcoded subject with example.com.
Definition job:
```
jobs:
  - name: "netdata.cloud"
    url: https://netdata.cloud/
    update_every: 120
    timeout: 60
    status_accepted: [400]

```
Example subject: Critical, httpcheck_web_service_unreachable = 100 %, on example.com

Expected: Critical, httpcheck_web_service_unreachable = 100 %, on {jobs.url}	

The solution seems, replace a templete with url property from job. Thanks
