### ISSUE TITLE
[Feat]: support different update every for each Prometheus collector job

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#767]
### Problem

I would like to have to different Prometheus collector jobs run with different `update_every`. 

At the moment i think we can only set the `update_every` for the collector as a whole as opposed to specific for each Prometheus job.

### Description

Ability to define update every at job level like this:

```
jobs:
  - name: node_exporter_demo
    url: https://node.demo.do.prometheus.io/metrics
    update_every: 15

  - name: some_other_endpoint
    url: https://some.ip/metrics
    update_every: 30
```

So have 1 job be 15 secs and the other 30 secs.

### Importance

really want

### Value proposition

1. finer grain control/config on Prometheus jobs.

**Comment by ilyam8** [comment]
This is supported. `update_every` can be set both for all jobs and for each in particular.

```yaml
update_every: 10

jobs:
  - name: node_exporter_demo
    url: https://node.demo.do.prometheus.io/metrics
    update_every: 15

  - name: some_other_endpoint
    url: https://some.ip/metrics
```

- node_exporter_demo will use 15
- some_other_endpoint 10
